modbus:
  - name: hru_atrea_rd5
    type: tcp
    host: IP_ADDRESS
    port: 502
    sensors:
      - name: "Rekuperace: aktuální požadovaný výkon"
        unique_id: hru_requested_power_value
        slave: 1
        input_type: holding
        address: 10704
        unit_of_measurement: '%'
        device_class: power_factor
        scan_interval: 10
      - name: "Rekuperace: aktuální požadovaná teplota"
        unique_id: hru_requested_temperature_value
        slave: 1
        scale: 0.1
        precision: 1
        input_type: holding
        address: 10706
        unit_of_measurement: '°C'
        device_class: temperature
        scan_interval: 10

input_number:
  hru_requested_power:
    name: "Rekuperace: požadovaný výkon"
    min: 12
    max: 100
    initial: 40
    step: 2
    unit_of_measurement: "%"
    mode: slider
    icon: "mdi:fan"
  hru_requested_temperature:
    name: "Rekuperace: požadovaná teplota"
    min: 10
    max: 40
    initial: 22.5
    step: 0.5
    unit_of_measurement: "°C"
    mode: slider
    icon: "mdi:thermometer"
