mqtt:
  - number:
      name: Luftator - klapka 01
      object_id: luftator_valve1
      state_topic: luftator/valves/valve1/state
      command_topic: luftator/valves/valve1/set
      min: 0
      max: 90
      step: 5
  - number:
      name: Luftator - klapka 02
      object_id: luftator_valve2
      state_topic: luftator/valves/valve2/state
      command_topic: luftator/valves/valve2/set
      min: 0
      max: 90
      step: 5
  - number:
      name: Luftator - klapka 03
      object_id: luftator_valve3
      state_topic: luftator/valves/valve3/state
      command_topic: luftator/valves/valve3/set
      min: 0
      max: 90
      step: 5
  - number:
      name: Luftator - klapka 04
      object_id: luftator_valve4
      state_topic: luftator/valves/valve4/state
      command_topic: luftator/valves/valve4/set
      min: 0
      max: 90
      step: 5
  - number:
      name: Luftator - klapka 05
      object_id: luftator_valve5
      state_topic: luftator/valves/valve5/state
      command_topic: luftator/valves/valve5/set
      min: 0
      max: 90
      step: 5
  - number:
      name: Luftator - klapka 06
      object_id: luftator_valve6
      state_topic: luftator/valves/valve6/state
      command_topic: luftator/valves/valve6/set
      min: 0
      max: 90
      step: 5
  - number:
      name: Luftator - klapka 07
      object_id: luftator_valve7
      state_topic: luftator/valves/valve7/state
      command_topic: luftator/valves/valve7/set
      min: 0
      max: 90
      step: 5
  - number:
      name: Luftator - klapka 08
      object_id: luftator_valve8
      state_topic: luftator/valves/valve8/state
      command_topic: luftator/valves/valve8/set
      min: 0
      max: 90
      step: 5
  - number:
      name: Luftator - klapka 09
      object_id: luftator_valve9
      state_topic: luftator/valves/valve9/state
      command_topic: luftator/valves/valve9/set
      min: 0
      max: 90
      step: 5
  - number:
      name: Luftator - klapka 10
      object_id: luftator_valve10
      state_topic: luftator/valves/valve10/state
      command_topic: luftator/valves/valve10/set
      min: 0
      max: 90
      step: 5
  - number:
      name: Luftator - klapka 11
      object_id: luftator_valve11
      state_topic: luftator/valves/valve11/state
      command_topic: luftator/valves/valve11/set
      min: 0
      max: 90
      step: 5
  - number:
      name: Luftator - klapka 12
      object_id: luftator_valve12
      state_topic: luftator/valves/valve12/state
      command_topic: luftator/valves/valve12/set
      min: 0
      max: 90
      step: 5
